FROM node:18-alpine

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package*.json ./

# Устанавливаем зависимости
RUN npm ci --only=production

# Копируем исходный код
COPY . .

# Открываем порт
EXPOSE 3001

# Создаем запускающий скрипт
COPY start.sh /app/start.sh
RUN chmod +x /app/start.sh

# Запускаем через скрипт
CMD ["/app/start.sh"] 